### ISSUE TITLE
Unhandled exception causes fatal error when API secret isn't set

### ISSUE THREAD

**Issue by jslegers** [sumocoders/Teamleader#20]
Because I had a typo in the field name referencing my API secret, I get the following fatal error:

> ### Additional uncaught exception thrown while handling exception.
> #### Original
> 
> SumoCoders\Teamleader\Exception: api-error on group 6151 in SumoCoders\Teamleader\Teamleader->doCall() (line 272 of /Users/inxco/Documents/www/drupalteamleader4/sites/all/vendor/SumoCoders/Teamleader/Teamleader.php).
> #### Additional
> 
> Exception: theme() may not be called until all modules are loaded. in theme() (line 1017 of /Users/inxco/Documents/www/drupalteamleader4/includes/theme.inc).

It would be nice to trigger a more user friendly error message when an API secret or API group has not been defined instead of this error.

**Comment by carakas** [comment]
@jslegers can you create a PR for this if this is still an issue?

**Comment by jslegers** [comment]
@carakas :

I no longer have a working Teamleader account nor any interest in using this library.

Heck, I haven't even been doing any PHP coding in months ;-)

**Comment by carakas** [comment]
Ok then I'll close this issue

**Comment by jslegers** [comment]
@carakas :

Shouldn't you first test whether you can reproduce the error before you close the issue?
I seriously doubt it has been fixed!

**Comment by carakas** [comment]
@jslegers they are constructor parameters, so in my opinion we can expect them to be there

**Comment by jslegers** [comment]
@carakas :

**After** your initial setup, yes, you can expect them to be there.

A lot can go wrong **during** the initial setup, however, and useful help messages at this stage would make everyone's lives easier ;-)

**Comment by carakas** [comment]
I'll reopen it

**Comment by carakas** [comment]
I still don't see how this could happen, since the initial setup is literally passing those values to the constructor

**Comment by turanct** [comment]
It doesn't seem like the teamleader API lets us know that an *authentication error* occured? In that case, displaying the error they return is the only thing we can do... The only thing they let us know is:

1. request was succesful `code 200`
2. request failed `code 400`
3. rate limits reached `code 505`

which aren't even great http response codes

Furthermore, we can't check for correctness of the parameters when constructing the instance, so it seems to me like throwing an exception like this is the only reasonable way to go?

**Comment by jslegers** [comment]
This error takes place when there's a mistake in your API secret or API group.

As I explained (in the first line), it happened to me :
> Because I had a typo in the field name referencing my API secret, I get the following fatal error:
>
> [...]
